mode: train
lmdb: False #True
dry_run: False
rgb_dir: './datasets/rgb'
lmdb_dir: './datasets/lmdb'
dataset_json_folder: '/home/rz/DeepfakeBench/preprocessing/dataset_json' # '../preprocessing/dataset_json/'
SWA: False
save_avg: False # save the avg of all train_sets (?)
log_dir: /home/rz/DeepfakeBench/training/results #./logs/training/
# label settings
label_dict:
  # # DFD
  # DFD_fake: 1
  # DFD_real: 0
  # # FF++ + FaceShifter(FF-real+FF-FH)
  # FF-SH: 1
  # FF-F2F: 1
  # FF-DF: 1
  # FF-FS: 1
  # FF-NT: 1
  # FF-FH: 1
  # FF-real: 0
  # # CelebDF
  # CelebDFv1_real: 0
  # CelebDFv1_fake: 1
  # CelebDFv2_real: 0
  # CelebDFv2_fake: 1
  # # DFDCP
  # DFDCP_Real: 0
  # DFDCP_FakeA: 1
  # DFDCP_FakeB: 1
  # # DFDC
  # DFDC_Fake: 1
  # DFDC_Real: 0
  # # DeeperForensics-1.0
  # DF_fake: 1
  # DF_real: 0
  # # UADFV
  # UADFV_Fake: 1
  # UADFV_Real: 0
  # # Roop
  # roop_Real: 0
  # roop_Fake: 1

  # ------------------------- #
  # user_faces
  real: 0
  fake: 1
  # # gotcha
  gotcha_real: 0
  gotcha_fake: 1
  # ------------------------- #