# log dir 
log_dir: /home/rz/DeepfakeBench/training/results/ #/home/rz/DeepfakeBench/preprocessing/logs #/data/home/zhiyuanyan/DeepfakeBench/logs/testing_bench

# model setting
pretrained: /home/rz/DeepfakeBench/training/pretrained/xception_best.pth #/data/home/zhiyuanyan/DeepfakeBench/training/pretrained/xception-b5690688.pth   # path to a pre-trained model, if using one
model_name: xception   # model name
backbone_name: xception  # backbone name

#backbone setting
backbone_config:
  mode: original #adjust_channel_iid #original
  num_classes: 2
  inc: 3
  dropout: false #0.1 #0.2 #false

# dataset
all_dataset: [occlusion, no_occlusion, gotcha_occlusion, gotcha_no_occlusion]
#[FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT, FaceShifter, DeepFakeDetection, Celeb-DF-v1, Celeb-DF-v2, DFDCP, DFDC, DeeperForensics-1.0, UADFV, occlusion, no_occlusion, gotcha_occlusion, gotcha_no_occlusion]
train_dataset: [gotcha_occlusion] #[FaceForensics++]
test_dataset: [gotcha_occlusion] #[FaceForensics++, DeepFakeDetection]

compression: c23  # compression-level for videos
train_batchSize: 32   # training batch size
test_batchSize: 32   # test batch size
workers: 8   # number of data loading workers
frame_num: {'train': 32, 'test': 32} # default frame_num
# frame_num: {'train': 200, 'test': 200} #{'train': 32, 'test': 32}   # number of frames to use per video in training and testing
# frame_num: {'train': 'all', 'test': 500} # all  
# frame_num: {'train': 100, 'test': 100}
# 100 ok, 200ok, 300 boh, 'all' killed
resolution: 256   # resolution of output image to network
with_mask: false   # whether to include mask information in the input
with_landmark: false   # whether to include facial landmark information in the input


# data augmentation
use_data_augmentation: true  # Add this flag to enable/disable data augmentation
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.0
  rotate_limit: [-10, 10]
  blur_prob: 0.5
  blur_limit: [3, 7]
  brightness_prob: 0.5
  brightness_limit: [-0.1, 0.1]
  contrast_limit: [-0.1, 0.1]
  quality_lower: 40
  quality_upper: 100

# mean and std for normalization
mean: [0.5, 0.5, 0.5]
std: [0.5, 0.5, 0.5]

# optimizer config
optimizer:
  # choose between 'adam' and 'sgd'
  type: adam
  adam:
    lr: 0.0002  # learning rate
    beta1: 0.9  # beta1 for Adam optimizer
    beta2: 0.999 # beta2 for Adam optimizer
    eps: 0.00000001  # epsilon for Adam optimizer
    weight_decay: 0.0005  # weight decay for regularization
    amsgrad: false
  sgd:
    lr: 0.0002  # learning rate
    momentum: 0.9  # momentum for SGD optimizer
    weight_decay: 0.0005  # weight decay for regularization

# training config
lr_scheduler: null   # learning rate scheduler
# -------------------------------------------- #
# lr_scheduler: step   # learning rate scheduler
# lr_step: 2 # 1 
# lr_gamma: 0.1
# -------------------------------------------- #
# lr_scheduler: cosine   # CosineAnnealingLR scheduler
# lr_T_max: 10   # number of epochs for learning rate to reach 0
# lr_eta_min: 0   # minimum learning rate value
# -------------------------------------------- #
# lr_scheduler: linear   # Linear LR scheduler
# -------------------------------------------- #
nEpochs: 10 #15   # number of epochs to train for
start_epoch: 0   # manual epoch number (useful for restarts)
save_epoch: 1   # interval epochs for saving models
rec_iter: 100   # interval iterations for recording
logdir: ./logs   # folder to output images and logs
manualSeed: 1024   # manual seed for random number generation
save_ckpt: true   # whether to save checkpoint
save_feat: true   # whether to save features

# loss function
loss_func: focal_loss #cross_entropy   # loss function to use
losstype: null

# metric
metric_scoring: acc #auc   # metric for evaluation (auc, acc, eer, ap)

# cuda

cuda: true   # whether to use CUDA acceleration
cudnn: true   # whether to use CuDNN for convolution operations